{
 "title": "New Agoric Validator Daskboard - by EarnX",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "instanceName", "query": "vps04:9100" },
   { "name": "interface", "query": "eth0" }
  ]
 },
 "panels": [
  {
   "title": "Tendermint Block Time (sec) - 95% percentil ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(tendermint_consensus_block_interval_seconds_bucket[30s])) by (le))"
    }
   ]
  },
  {
   "title": "My Validator Missed Blocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_validator_missed_blocks"
    }
   ]
  },
  {
   "title": "Blockchain Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_latest_block_height",
     "legendFormat": "height"
    }
   ]
  },
  {
   "title": "Last Blockchain Height Signed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validator_last_signed_height",
     "legendFormat": "height"
    }
   ]
  },
  {
   "title": "CPU Pressure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "rate(node_pressure_cpu_waiting_seconds_total{instance=\"$instanceName\"}[30s])*1000"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$instanceName\"}",
     "legendFormat": "RAM free"
    }
   ]
  },
  {
   "title": "My Validator Connected Peers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tendermint_p2p_peers", "legendFormat": "connected peers" }
   ]
  },
  {
   "title": "Internet Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"$interface\", instance=\"$instanceName\"}[30s])*8\n",
     "legendFormat": "tx"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"$interface\", instance=\"$instanceName\"}[30s])*8",
     "legendFormat": "rx"
    }
   ]
  },
  {
   "title": "Disk Read & Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=\"$instanceName\"}[30s])\n",
     "legendFormat": "read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=\"$instanceName\"}[30s])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Disk Available",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_avail_bytes{instance=\"$instanceName\", mountpoint=\"/\"})/(1024*1024*1024)"
    }
   ]
  }
 ]
}